#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

use std::process::Command;
use std::io::Write;
use tempfile::NamedTempFile;

#[tauri::command]
fn get_serial_ports() -> Vec<String> {
    serialport::available_ports()
        .map(|ports| ports.into_iter().map(|p| p.port_name).collect())
        .unwrap_or_else(|_| vec![])
}

#[tauri::command]
async fn run_flash_command() -> Result<String, String> {
    let output = Command::new("uptime")
        .output()
        .map_err(|e| e.to_string())?;
    Ok(String::from_utf8_lossy(&output.stdout).to_string())
}

#[tauri::command]
async fn silent_print(pdf_data: Vec<u8>, _page_height_mm: f64) -> Result<String, String> {
    let mut temp_file = NamedTempFile::new().map_err(|e| e.to_string())?;
    temp_file.write_all(&pdf_data).map_err(|e| e.to_string())?;

    // Important: the PDF generated by the app already has the exact label size.
    // Force portrait/no-rotation in CUPS to prevent flipped output on label printers.
    let output = Command::new("lp")
        .arg("-o")
        .arg("orientation-requested=3")
        .arg(temp_file.path())
        .output()
        .map_err(|e| e.to_string())?;

    if output.status.success() {
        Ok("Print job sent successfully".into())
    } else {
        Err(String::from_utf8_lossy(&output.stderr).to_string())
    }
}

fn main() {
    tauri::Builder::default()
        .invoke_handler(tauri::generate_handler![
            get_serial_ports, 
            silent_print, 
            run_flash_command
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
